### ISSUE TITLE
Does it support Teensy 4.1?

### ISSUE THREAD

**Issue by Gymnast544** [LAtimes2/TeensyLogicAnalyzer#6]

**Comment by LAtimes2** [comment]
It should but I haven't tested it yet. Maybe I will solder the pins on my 4.1 and try it tomorrow. :)

**Comment by Gymnast544** [comment]
That would help so much with a project I'm working on! Thank you!

**Comment by LAtimes2** [comment]
It required a minor tweak for Teensy 4.1. Just released another beta version. Version with full support for Teensy 4.x is coming in a week or three.

**Comment by sumondhara** [comment]
It would be a great help if 8 channel support is obtained for Teensy 4.1. 
As I purchased the same for the logic analyzer purpose only.

**Comment by LAtimes2** [comment]
8 channel support was almost done and then it went down in priority. I will release what I have as a preliminary release and bump up the priority of finishing it. [I'm a perfectionist, so the preliminary version is 95% complete - just some quirks in edge conditions.]

**Comment by sumondhara** [comment]
Thank you very much, Sir.

**Comment by LAtimes2** [comment]
Version 4.2 of the logic analyzer has been released. It supports 8 channels for Teensy 4 on pins 14-21, in order.

**Comment by sumondhara** [comment]
Thank you very much, Sir. It works perfectly for my requirement.
